name:                icml21
version:             0.1.0.0
license:             BSD3

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/icml21#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - hashable
  - unordered-containers
  - containers
  - aeson
  - text
  - bytestring
  - directory
  - regex-tdfa
  - filepath
  - random
  - mtl

executables:
  icml21-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    dependencies:
    - icml21
    - async
    - directory
    - hashable

tests:
  icml21-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icml21
